---
title: "1_raw_pop"
author: "zhendong yuan"
date: "2019/9/10"
output: html_document
---

```{r setup, results='hide', message=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("rgdal")
library("sp")
library("dplyr")
library("data.table")
library("mapview")
```

# merge mid boundary data with population csv

```{r}
london_mid <- readOGR("/data/zhendongBackup/london/20191213/MSOA_2011_London_3857.shp")
head(london_mid@data)
london_mid$MSOA11CD = as.character(london_mid$MSOA11CD)

population_mid_england = read.csv("/data/zhendongBackup/london/20191213/Rspace/pop/2015_pop_england_mid.csv")
head(population_mid_england)
population_mid_england$Area.Codes = as.character(population_mid_england$Area.Codes)

pop_london_boundary = merge(population_mid_england,london_mid@data, by.x = "Area.Codes", by.y = "MSOA11CD", all.y = TRUE)

head(pop_london_boundary)
pop_london_boundary$Area.Names = NULL
pop_london_boundary$MSOA11NM = NULL
pop_london_boundary$LAD11CD = NULL
pop_london_boundary$LAD11NM = NULL
pop_london_boundary$RGN11CD = NULL
pop_london_boundary$RGN11NM = NULL
colnames(pop_london_boundary) = c("AreaCodes","detialedName","population","USUALRES","HHOLDRES",  "COMESTRES","POPDEN","HHOLDS","AVHHOLDSZ")


```


# merge low boundary data with population csv

```{r}
london_low <- readOGR("/data/zhendongBackup/london/20191213/LSOA_2011_London_3857.shp")
head(london_low@data)
london_low$LSOA11CD = as.character(london_low$LSOA11CD)

population_low_england = read.csv("/data/zhendongBackup/london/20191213/Rspace/pop/2015_pop_low.csv")
head(population_low_england)
population_low_england$AreaCodes = as.character(population_low_england$AreaCodes)

pop_london_low_boundary = merge(population_low_england,london_low@data, by.x = "AreaCodes", by.y = "LSOA11CD", all.y = TRUE)

head(pop_london_low_boundary)
pop_london_low_boundary$Area.Names = NULL
pop_london_low_boundary$MSOA11NM = NULL
pop_london_low_boundary$LAD11CD = NULL
pop_london_low_boundary$LAD11NM = NULL
pop_london_low_boundary$RGN11CD = NULL
pop_london_low_boundary$RGN11NM = NULL
pop_london_low_boundary$LSOA11NM = NULL
pop_london_low_boundary$MSOA11CD = NULL
colnames(pop_london_low_boundary) = c("AreaCodes","detialedName","population","USUALRES","HHOLDRES",  "COMESTRES","POPDEN","HHOLDS","AVHHOLDSZ")

```
# plot distribution
```{r}
plot(density(pop_london_low_boundary$population),col = "green")
lines(density(pop_london_boundary$population),col = "black")

```
# save data
```{r}
save(pop_london_boundary,file ="raw_pop_mid_london.Rdata")
save(pop_london_low_boundary,file ="raw_pop_london_low.Rdata")
```


