---
title: "1_enriched_population_merged"
author: "********"
date: "2019/9/21"
output: html_document
---

```{r setup, results='hide', message=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("rgdal")
library("sp")
library("dplyr")
library("data.table")
library("mapview")
```

# create moa_enriched_covariates.Rdata

```{r}
# at here the scaled_moa_feature.Rdata stands for only scaled populaiton 
moa_data_shape <- readOGR("/home/z/********/london/enriched_feature/moa_enriched.shp")
moa_data = moa_data_shape@data
colnames(moa_data)
#merge /home/z/********/london/Rspace/pop/raw_pop_mid_london.Rdata
raw_pop_mid_london = get(load("/home/z/********/london/Rspace/pop/raw_pop_mid_london.Rdata"))
colnames(raw_pop_mid_london)
moa_data_df = merge(moa_data,raw_pop_mid_london, by.x = "MSOA11CD" ,by.y = "AreaCodes")
colnames(moa_data_df)
moa_data = moa_data_df[,c(13:47,49)]
# summary the raw data
moa_data$TWEETS_DIS = as.numeric(as.character(moa_data$TWEETS_DIS))
moa_data$DISTINCT_T = as.numeric(as.character(moa_data$DISTINCT_T))
summary(moa_data)
moa_data[is.na(moa_data)] <- 0
#pop = moa_data$population
#summary(moa_data)
moa_data = as.data.frame(normalize(moa_data,method = "range",range = c(0, 1)))
plot(density(moa_data$B_NUMBER))
summary(moa_data)
save(moa_data,file = "/home/z/********/london/enriched_feature/moa_enriched_covariates.Rdata")


```


# create loa_enriched_covariates.Rdata

```{r}
# at here the scaled_moa_feature.Rdata stands for only scaled populaiton 
loa_data_shape <- readOGR("/home/z/********/london/enriched_feature/loa_enriched.shp")
loa_data = loa_data_shape@data
colnames(loa_data)
summary(loa_data)
#merge /home/z/********/london/Rspace/pop/raw_pop_mid_london.Rdata
raw_pop_loa_london = get(load("/home/z/********/london/Rspace/pop/raw_pop_london_low.Rdata"))
colnames(raw_pop_loa_london)
loa_data_df = merge(loa_data,raw_pop_loa_london, by.x = "LSOA11CD" ,by.y = "AreaCodes")
colnames(loa_data_df)
loa_data = loa_data_df[,c(15:34,36:50,52)]
# summary the raw data
loa_data$TWEETS_DIS = as.numeric(as.character(loa_data$TWEETS_DIS))
loa_data$DISTINCT_T = as.numeric(as.character(loa_data$DISTINCT_T))
summary(loa_data)
loa_data[is.na(loa_data)] <- 0

loa_data = as.data.frame(normalize(loa_data,method = "range",range = c(0, 1)))
plot(density(loa_data$B_NUMBER))
summary(loa_data)

```

```{r}
colnames(moa_data)
colnames(loa_data)


colnames(loa_data)[c(12:15,21,29)] = c("MOA_AREA_4","MOA_PERIME","MOA_FRACTA","MOA_SHAPE","MOA_B_RATI","SBRO_STDDE")


loa_data_reordered = loa_data[,c(1:16,29:31,28,32:34,17:20,24:27,21:23,35:36)]
colnames(loa_data_reordered)
save(moa_data,file = "/home/z/********/london/enriched_feature/moa_enriched_covariates.Rdata")
save(loa_data_reordered,file = "/home/z/********/london/enriched_feature/loa_enriched_covariates.Rdata")

```


# create sbl_enriched_covariates.Rdata
```{r}
# at here the scaled_moa_feature.Rdata stands for only scaled populaiton 
sbl_data_shape <- readOGR("/home/z/********/london/enriched_feature/street_blocksl_withinloa.shp")
sbl_data = sbl_data_shape@data
colnames(sbl_data)
summary(sbl_data)
sbl_data$LSOA11CD = NULL
sbl_data = sbl_data[,c(4:38)]
# summary the raw data
sbl_data$TWEETS_DIS = as.numeric(as.character(sbl_data$TWEETS_DIS))
sbl_data$DISTINCT_T = as.numeric(as.character(sbl_data$DISTINCT_T))

summary(sbl_data)
sbl_data[is.na(sbl_data)] <- 0

sbl_data = as.data.frame(normalize(sbl_data,method = "range",range = c(0, 1)))
plot(density(sbl_data$B_NUMBER))
summary(sbl_data)
```

```{r}
colnames(sbl_data)[c(1:4,16,29)] = c("MOA_AREA_4","MOA_PERIME","MOA_FRACTA","MOA_SHAPE","MOA_B_RATI","SBRO_STDDE")
# reorder
sbl_data=sbl_data[,c(5:15,1,2,4,3,22,29:31,28,19:21,24:27,32:35,16:18,23)]
colnames(sbl_data)



save(sbl_data,file = "/home/z/********/london/enriched_feature/sbl_enriched_covariates.Rdata")
```

