---
title: "integrateCompare_xgboost"
author: "**********"
date: "2019/11/2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("ggplot2")
```

# integrate baseline moa2loa DNN directly applied.
```{r}
moa2loa_Xgboost_direct = NULL
for (i in c(1:50))
{ 
  moa2loa_Xgboost_direct = rbind(moa2loa_Xgboost_direct,get(load(paste("/home/z/*********/london/enriched_feature/moa2loa_xgboost_CV/",i,"_moa2loa_Xgboost.Rdata",sep = ""))))
}

summary(moa2loa_Xgboost_direct)
```

# integrate moa2loa DNN adaptation uLSIF
```{r}
moa2loa_Xgboost_uLSIF = NULL
for (i in c(1:50))
{ 
  moa2loa_Xgboost_uLSIF = rbind(moa2loa_Xgboost_uLSIF,get(load(paste("/home/z/*********/london/enriched_feature/moa2loa_xgboost_CV/uLSIF/",i,"_moa2loa_Xgboost_uLSIF.Rdata",sep = ""))))
}

summary(moa2loa_Xgboost_uLSIF)
```


# integrate moa2loa DNN adaptation RuLSIF
```{r}
moa2loa_Xgboost_RuLSIF = NULL
for (i in c(1:50))
{ 
  moa2loa_Xgboost_RuLSIF = rbind(moa2loa_Xgboost_RuLSIF,get(load(paste("/home/z/*********/london/enriched_feature/moa2loa_xgboost_CV/RuLSIF/",i,"_moa2loa_Xgboost_RuLSIF.Rdata",sep = ""))))
}
summary(moa2loa_Xgboost_RuLSIF)
```


# integrate moa2loa DNN adaptation KLIEP
```{r}
moa2loa_Xgboost_KLIEP = NULL
for (i in c(1:50))
{ 
  moa2loa_Xgboost_KLIEP = rbind(moa2loa_Xgboost_KLIEP,get(load(paste("/home/z/*********/london/enriched_feature/moa2loa_xgboost_CV/KLIEP/",i,"_moa2loa_Xgboost_KLIEP.Rdata",sep = ""))))
}
summary(moa2loa_Xgboost_KLIEP)
```
# store the data
```{r}
save(moa2loa_Xgboost_direct,file="/home/z/*********/london/enriched_feature/moa2loa_xgboost_CV/moa2loa_Xgboost_direct.Rdata")
save(moa2loa_Xgboost_uLSIF,file="/home/z/*********/london/enriched_feature/moa2loa_xgboost_CV/moa2loa_Xgboost_uLSIF.Rdata")
save(moa2loa_Xgboost_RuLSIF,file="/home/z/*********/london/enriched_feature/moa2loa_xgboost_CV/moa2loa_Xgboost_RuLSIF.Rdata")
save(moa2loa_Xgboost_KLIEP,file="/home/z/*********/london/enriched_feature/moa2loa_xgboost_CV/moa2loa_Xgboost_KLIEP.Rdata")
```

# visualize in boxplot 
```{r}
boxplot( moa2loa_Xgboost_direct$s_rmse,moa2loa_Xgboost_uLSIF$s_rmse,moa2loa_Xgboost_RuLSIF$s_rmse,moa2loa_Xgboost_KLIEP$s_rmse)
boxplot( moa2loa_Xgboost_direct$s_prmse,moa2loa_Xgboost_uLSIF$s_prmse,moa2loa_Xgboost_RuLSIF$s_prmse,moa2loa_Xgboost_KLIEP$s_prmse)
boxplot( moa2loa_Xgboost_direct$s_mae,moa2loa_Xgboost_uLSIF$s_mae,moa2loa_Xgboost_RuLSIF$s_mae,moa2loa_Xgboost_KLIEP$s_mae)
boxplot( moa2loa_Xgboost_direct$s_pmae,moa2loa_Xgboost_uLSIF$s_pmae,moa2loa_Xgboost_RuLSIF$s_pmae,moa2loa_Xgboost_KLIEP$s_pmae)

boxplot( moa2loa_Xgboost_direct$d_mae,moa2loa_Xgboost_uLSIF$d_mae,moa2loa_Xgboost_RuLSIF$d_mae,moa2loa_Xgboost_KLIEP$d_mae)
boxplot( moa2loa_Xgboost_direct$d_pmae,moa2loa_Xgboost_uLSIF$d_pmae,moa2loa_Xgboost_RuLSIF$d_pmae,moa2loa_Xgboost_KLIEP$d_pmae)
boxplot( moa2loa_Xgboost_direct$d_rmse,moa2loa_Xgboost_uLSIF$d_rmse,moa2loa_Xgboost_RuLSIF$d_rmse,moa2loa_Xgboost_KLIEP$d_rmse)
boxplot( moa2loa_Xgboost_direct$d_prmse,moa2loa_Xgboost_uLSIF$d_prmse,moa2loa_Xgboost_RuLSIF$d_prmse,moa2loa_Xgboost_KLIEP$d_prmse)

```


# calculate percentage of boosting
```{r}
s_rmse_boost =data.frame(uLSIF=(mean(moa2loa_Xgboost_direct$s_rmse)-mean(moa2loa_Xgboost_uLSIF$s_rmse))/mean(moa2loa_Xgboost_direct$s_rmse),
                      RuLSIF=(mean(moa2loa_Xgboost_direct$s_rmse)-mean(moa2loa_Xgboost_RuLSIF$s_rmse))/mean(moa2loa_Xgboost_direct$s_rmse),
                         KLIEP=(mean(moa2loa_Xgboost_direct$s_rmse)-mean(moa2loa_Xgboost_KLIEP$s_rmse))/mean(moa2loa_Xgboost_direct$s_rmse))
s_rmse_boost

s_mae_boost =data.frame(uLSIF=(mean(moa2loa_Xgboost_direct$s_mae)-mean(moa2loa_Xgboost_uLSIF$s_mae))/mean(moa2loa_Xgboost_direct$s_mae),
                        RuLSIF=(mean(moa2loa_Xgboost_direct$s_mae)-mean(moa2loa_Xgboost_RuLSIF$s_mae))/mean(moa2loa_Xgboost_direct$s_mae),
                         KLIEP=(mean(moa2loa_Xgboost_direct$s_mae)-mean(moa2loa_Xgboost_KLIEP$s_mae))/mean(moa2loa_Xgboost_direct$s_mae))
s_mae_boost

d_rmse_boost =data.frame(uLSIF=(mean(moa2loa_Xgboost_direct$d_rmse)-mean(moa2loa_Xgboost_uLSIF$d_rmse))/mean(moa2loa_Xgboost_direct$d_rmse),
                       RuLSIF=(mean(moa2loa_Xgboost_direct$d_rmse)-mean(moa2loa_Xgboost_RuLSIF$d_rmse))/mean(moa2loa_Xgboost_direct$d_rmse),
                         KLIEP=(mean(moa2loa_Xgboost_direct$d_rmse)-mean(moa2loa_Xgboost_KLIEP$d_rmse))/mean(moa2loa_Xgboost_direct$d_rmse))
d_rmse_boost

d_mae_boost =data.frame(uLSIF=(mean(moa2loa_Xgboost_direct$d_mae)-mean(moa2loa_Xgboost_uLSIF$d_mae))/mean(moa2loa_Xgboost_direct$d_mae),
                        RuLSIF=(mean(moa2loa_Xgboost_direct$d_mae)-mean(moa2loa_Xgboost_RuLSIF$d_mae))/mean(moa2loa_Xgboost_direct$d_mae),
                         KLIEP=(mean(moa2loa_Xgboost_direct$d_mae)-mean(moa2loa_Xgboost_KLIEP$d_mae))/mean(moa2loa_Xgboost_direct$d_mae))
d_mae_boost

```

